<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('posts')->delete();
        
        \DB::table('posts')->insert(array (
            0 => 
            array (
                'ID' => 1,
                'post_author' => 1,
                'post_date' => '2023-07-03 18:47:50',
                'post_date_gmt' => '2023-07-03 18:47:50',
                'post_content' => '<p>Isto é o conteudo da página home<br></p>',
                'post_title' => 'home',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'home',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 14:00:44',
                'post_modified_gmt' => '2023-07-03 18:47:50',
                'post_content_filtered' => NULL,
                'post_parent' => 8,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"principal"}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64a341f536abf',
            ),
            1 => 
            array (
                'ID' => 2,
                'post_author' => 1,
                'post_date' => '2023-07-04 08:56:51',
                'post_date_gmt' => '2023-07-04 08:56:51',
                'post_content' => '<div class="row mt-4">
<div class="col-lg-12 col-md-6 mb-4">
[sc ac="form_leilao"]
</div>

<div class="col-lg-4 col-md-6 mb-4">

</div>
</div>',
                'post_title' => 'leilão create',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'leilao-create',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 14:01:48',
                'post_modified_gmt' => '2023-07-04 08:56:51',
                'post_content_filtered' => NULL,
                'post_parent' => 8,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria","permission":["1","2","3","5"]}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64a408ed8c6c5',
            ),
            2 => 
            array (
                'ID' => 3,
                'post_author' => 1,
                'post_date' => '2023-08-01 16:47:19',
                'post_date_gmt' => '2023-08-01 16:47:19',
                'post_content' => '[sc ac="list_lance_user"]',
                'post_title' => 'Lances',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'lances-list',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 15:24:42',
                'post_modified_gmt' => '2023-07-06 16:47:19',
                'post_content_filtered' => NULL,
                'post_parent' => 8,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria","permission":["1","2","3","5"]}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64a719e8e3f01',
            ),
            3 => 
            array (
                'ID' => 4,
                'post_author' => 1,
                'post_date' => '2024-01-12 15:36:09',
                'post_date_gmt' => '2024-01-12 15:36:09',
                'post_content' => '<section class="bg-light">
<div class="container py-5">
<div class="row">
<div class="col-12 col-lg-6 py-5 text-center text-lg-start">
<h2>Passo 01</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce pharetra tincidunt magna, et sagittis neque dignissim non. Mauris felis ligula, molestie et facilisis vitae, egestas ut metus.</p>
</div>
<div class="col-12 col-lg-6">
<a class="venobox youtube-video vbox-item" data-autoplay="true" data-vbtype="video" href="https://www.youtube.com/watch?v=BZAN-i_o8nA&amp;t=5s">
<i class="fa fa-play"></i>
<div class="youtube-video-overlay rounded"></div>
<img class="rounded" src="https://leilao.aeroclubejf.com.br/images/leilao-aeroclube-de-juiz-de-fora.jpg" alt="">
</a>
</div>
</div>
</div>
</section>
<section class="theme-bg-primary">
<div class="container py-5">
<div class="row">
<div class="order-1 order-lg-0 col-12 col-lg-6">
<a class="venobox youtube-video vbox-item" data-autoplay="true" data-vbtype="video" href="https://www.youtube.com/watch?v=BZAN-i_o8nA&amp;t=5s">
<i class="fa fa-play"></i>
<div class="youtube-video-overlay rounded"></div>
<img class="rounded" src="https://leilao.aeroclubejf.com.br/images/leilao-aeroclube-de-juiz-de-fora.jpg" alt="">
</a>
</div>
<div class="order-0 order-lg-1 col-12 col-lg-6 py-5 text-light text-center text-lg-start">
<h2>Passo 02</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce pharetra tincidunt magna, et sagittis neque dignissim non. Mauris felis ligula, molestie et facilisis vitae, egestas ut metus.</p>
</div>
</div>
</div>
</section>
<section class="bg-light">
<div class="container py-5">
<div class="row">
<div class="col-12 col-lg-6 py-5 text-center text-lg-start">
<h2>Passo 03</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce pharetra tincidunt magna, et sagittis neque dignissim non. Mauris felis ligula, molestie et facilisis vitae, egestas ut metus.</p>
</div>
<div class="col-12 col-lg-6">
<a class="venobox youtube-video vbox-item" data-autoplay="true" data-vbtype="video" href="https://www.youtube.com/watch?v=BZAN-i_o8nA&amp;t=5s">
<i class="fa fa-play"></i>
<div class="youtube-video-overlay rounded"></div>
<img class="rounded" src="https://leilao.aeroclubejf.com.br/images/leilao-aeroclube-de-juiz-de-fora.jpg" alt="">
</a>
</div>
</div>
</div>
</section>',
                'post_title' => 'Entenda como funciona',
                'post_excerpt' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu feugiat elit. Duis dapibus lorem nec nisi feugiat consequat. Aenean ac eros ut tortor consectetur pharetra. Vivamus luctus sit amet elit id imperdiet.',
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'entenda-como-funciona',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 16:17:49',
                'post_modified_gmt' => '2024-01-12 15:36:09',
                'post_content_filtered' => NULL,
                'post_parent' => 95,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"html"}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '65a185f19695e',
            ),
            4 => 
            array (
                'ID' => 5,
                'post_author' => 1,
                'post_date' => '2023-09-29 16:47:19',
                'post_date_gmt' => '2023-09-29 16:47:19',
                'post_content' => '<div class="row mt-4">
<div class="col-lg-12 col-md-6 mb-4">
[sc ac="agradecimento"]
</div>
</div>',
                'post_title' => 'Agradecimento',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'obrigado-pela-compra',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 15:13:58',
                'post_modified_gmt' => '2023-07-06 16:47:19',
                'post_content_filtered' => NULL,
                'post_parent' => 8,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria","permission":["1","2","3","5"]}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64a719e8e3d87',
            ),
            5 => 
            array (
                'ID' => 6,
                'post_author' => NULL,
                'post_date' => '2024-01-12 15:36:10',
                'post_date_gmt' => '2024-01-12 15:36:10',
                'post_content' => NULL,
                'post_title' => 'Entenda como funciona',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => '4',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 15:36:10',
                'post_modified_gmt' => '2024-01-12 15:36:10',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => 6,
                'post_type' => 'menu',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '65a1869ae1043',
            ),
            6 => 
            array (
                'ID' => 7,
                'post_author' => 1,
                'post_date' => '2023-07-06 00:00:00',
                'post_date_gmt' => '2023-07-06 09:47:25',
                'post_content' => NULL,
                'post_title' => NULL,
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'Banner_home.jpg',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-07-06 09:47:25',
                'post_modified_gmt' => '2023-07-06 09:47:25',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => 'media/2023/07/Banner_home.jpg',
                'menu_order' => NULL,
                'post_type' => 'attachment',
                'post_mime_type' => 'image/jpeg',
                'comment_count' => NULL,
                'config' => '"{\\"extenssao\\":\\"jpg\\"}"',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => NULL,
            ),
            7 => 
            array (
                'ID' => 8,
                'post_author' => 1,
                'post_date' => '2023-07-06 00:00:00',
                'post_date_gmt' => '2023-07-06 09:51:36',
                'post_content' => NULL,
                'post_title' => NULL,
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'AVIÃO-DECOLANDO.jpg',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-07-06 09:51:36',
                'post_modified_gmt' => '2023-07-06 09:51:36',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => 'media/2023/07/AVIÃO-DECOLANDO.jpg',
                'menu_order' => NULL,
                'post_type' => 'attachment',
                'post_mime_type' => 'image/jpeg',
                'comment_count' => NULL,
                'config' => '"{\\"extenssao\\":\\"jpg\\"}"',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => NULL,
            ),
            8 => 
            array (
                'ID' => 9,
                'post_author' => 1,
                'post_date' => '2023-08-01 16:47:19',
                'post_date_gmt' => '2023-08-01 16:47:19',
                'post_content' => '[sc ac="payment"]',
                'post_title' => 'Pagamentos',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'payment',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-02-01 11:13:50',
                'post_modified_gmt' => '2023-07-06 16:47:19',
                'post_content_filtered' => NULL,
                'post_parent' => 8,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria","permission":["1","2","3","5"]}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64a719e8e3d03',
            ),
            9 => 
            array (
                'ID' => 10,
                'post_author' => 1,
                'post_date' => '2023-10-19 19:50:10',
                'post_date_gmt' => '2023-10-19 19:50:10',
                'post_content' => '<section class="elementor-section elementor-top-section elementor-element elementor-element-ce68779 elementor-section-boxed elementor-section-height-default elementor-section-height-default" data-id="ce68779" data-element_type="section">
<div class="elementor-container elementor-column-gap-default">
<div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-4c17c50" data-id="4c17c50" data-element_type="column">
<div class="elementor-widget-wrap elementor-element-populated">
<div class="elementor-element elementor-element-b988fbc elementor-widget elementor-widget-theme-post-content" data-id="b988fbc" data-element_type="widget" data-widget_type="theme-post-content.default">
<div class="elementor-widget-container">

<p>Termos e Condições de Acesso ao Site do Aeroclube Juiz de Fora</p>



<p>Ao acessar o site do Aeroclube Juiz de Fora, você concorda em cumprir os seguintes termos e condições:</p>



<ol><li>Uso do Conteúdo: O conteúdo disponível no site do Aeroclube Juiz de 
Fora, incluindo textos, imagens, vídeos, documentos e outros materiais, é
protegido por direitos autorais e propriedade intelectual. Esse 
conteúdo é fornecido exclusivamente para fins informativos e pessoais, 
não sendo permitida sua reprodução, modificação, distribuição ou uso 
comercial sem autorização prévia por escrito do Aeroclube Juiz de Fora.</li><li>Responsabilidade pelo Uso: O acesso e uso do site do Aeroclube Juiz 
de Fora são de sua responsabilidade exclusiva. Você concorda em utilizar
o site de acordo com as leis aplicáveis e em respeitar os direitos de 
terceiros. O Aeroclube Juiz de Fora não se responsabiliza por quaisquer 
danos ou prejuízos decorrentes do uso inadequado, incorreto ou ilícito 
do site.</li><li>Precisão das Informações: O Aeroclube Juiz de Fora se esforça para 
fornecer informações precisas e atualizadas em seu site. No entanto, não
garantimos a exatidão, completude ou atualidade dessas informações. O 
uso das informações disponíveis no site é de sua responsabilidade e você
é encorajado a verificar a precisão das mesmas antes de tomar qualquer 
decisão ou ação com base nelas.</li><li>Links Externos: O site do Aeroclube Juiz de Fora pode conter links 
para sites de terceiros. Esses links são fornecidos apenas para 
conveniência e não implicam em qualquer endosso, aprovação ou 
responsabilidade pelo conteúdo desses sites. Ao acessar esses links, 
você estará sujeito aos termos e condições de uso desses sites externos.</li><li>Privacidade: Ao utilizar o site do Aeroclube Juiz de Fora, você 
concorda com a Política de Privacidade do site, que descreve como suas 
informações pessoais serão coletadas, armazenadas e utilizadas. 
Recomendamos que você leia atentamente a Política de Privacidade para 
entender como suas informações serão tratadas.</li><li>Alterações nos Termos e Condições: O Aeroclube Juiz de Fora se 
reserva o direito de modificar ou atualizar estes Termos e Condições a 
qualquer momento, sem aviso prévio. Recomendamos que você revise 
periodicamente esta página para estar ciente de quaisquer alterações.</li><li>Jurisdição: Estes Termos e Condições serão regidos pelas leis do 
Brasil. Qualquer disputa decorrente ou relacionada a estes Termos e 
Condições será submetida à jurisdição exclusiva dos tribunais 
competentes do Brasil.</li></ol>



<p>Ao acessar e utilizar o site do Aeroclube Juiz de Fora, você 
reconhece ter lido, compreendido e concordado com estes Termos e 
Condições. Caso você não concorde com estes termos, recomendamos que não
utilize o site.</p>
</div>
</div>
</div>
</div>
</div>
</section>',
                'post_title' => 'Termos do site',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'termos-do-site',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 15:25:22',
                'post_modified_gmt' => '2023-10-19 19:50:10',
                'post_content_filtered' => NULL,
                'post_parent' => 10,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria"}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '6531b274d2925',
            ),
            10 => 
            array (
                'ID' => 11,
                'post_author' => 1,
                'post_date' => '2023-11-10 13:52:44',
                'post_date_gmt' => '2023-11-10 13:52:44',
                'post_content' => '[sc ac="leilao_list_seguindo"]',
                'post_title' => 'Leilões que você segue',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'seguindo',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 15:54:07',
                'post_modified_gmt' => '2023-11-10 13:52:44',
                'post_content_filtered' => NULL,
                'post_parent' => 8,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria","permission":["1","2","3","4","5"]}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '654e5fc344a55',
            ),
            11 => 
            array (
                'ID' => 12,
                'post_author' => 1,
                'post_date' => '2023-07-06 16:47:19',
                'post_date_gmt' => '2023-07-06 16:47:19',
                'post_content' => '[sc ac="list_leilao"]',
                'post_title' => 'Leilão list',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'leilao-list',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-02-01 13:43:34',
                'post_modified_gmt' => '2023-07-06 16:47:19',
                'post_content_filtered' => NULL,
                'post_parent' => 95,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria","permission":["1","2","3","5"]}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64a719e8e3d00',
            ),
            12 => 
            array (
                'ID' => 13,
                'post_author' => 1,
                'post_date' => '2023-07-07 17:41:28',
                'post_date_gmt' => '2023-07-07 17:41:28',
                'post_content' => '[sc ac="form_leilao"]',
                'post_title' => 'Leilão edit',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'leilao-edit',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-02-01 13:43:49',
                'post_modified_gmt' => '2023-07-07 17:41:28',
                'post_content_filtered' => NULL,
                'post_parent' => 94,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria","permission":["1","2","3","5"]}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64a8785e33dec',
            ),
            13 => 
            array (
                'ID' => 14,
                'post_author' => 1,
                'post_date' => '2023-07-07 17:41:28',
                'post_date_gmt' => '2023-07-07 17:41:28',
                'post_content' => '[sc ac="form_meu_cadastro"]',
                'post_title' => 'Meu cadastro',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'meu-cadastro',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 15:30:29',
                'post_modified_gmt' => '2023-07-07 17:41:28',
                'post_content_filtered' => NULL,
                'post_parent' => 95,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria","permission":["1","2","3","5"]}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64a8785e34d2g',
            ),
            14 => 
            array (
                'ID' => 15,
                'post_author' => 1,
                'post_date' => '2023-09-20 16:47:19',
                'post_date_gmt' => '2023-09-20 16:47:19',
                'post_content' => '<div class="row mt-4">
<div class="col-lg-12 col-md-6 mb-4">
[sc ac="ger_user"]
</div>

<div class="col-lg-4 col-md-6 mb-4">

</div>
</div>',
                'post_title' => 'Cadastrar usuário',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'user',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-09-20 07:01:48',
                'post_modified_gmt' => '2023-07-06 16:47:19',
                'post_content_filtered' => NULL,
                'post_parent' => 3,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '[]',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64a719e8e4d10',
            ),
            15 => 
            array (
                'ID' => 18,
                'post_author' => 1,
                'post_date' => '2024-02-01 11:19:20',
                'post_date_gmt' => '2024-02-01 11:19:20',
                'post_content' => '[sc ac="form_contato"]',
                'post_title' => 'Contato',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'contato',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-02-01 11:21:19',
                'post_modified_gmt' => '2024-02-01 11:19:20',
                'post_content_filtered' => NULL,
                'post_parent' => 94,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"secundaria"}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '65bba75e079cc',
            ),
            16 => 
            array (
                'ID' => 24,
                'post_author' => 1,
                'post_date' => '2023-07-10 11:38:09',
                'post_date_gmt' => '2023-07-10 11:38:09',
                'post_content' => '<p>Contrato apenas<br></p>',
                'post_title' => 'Repasse do Contrato CPS.ACJF.ADM.2021.0948',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => NULL,
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-07-13 18:46:15',
                'post_modified_gmt' => '2023-07-10 11:38:09',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'produtos',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"cliente":"5","total_horas":"15","valor_r":"R$ 8.422,22"}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64ac17bac7827',
            ),
            17 => 
            array (
                'ID' => 27,
                'post_author' => NULL,
                'post_date' => '2023-07-10 14:43:03',
                'post_date_gmt' => '2023-07-10 14:43:03',
                'post_content' => NULL,
                'post_title' => 'leilão teste 5',
                'post_excerpt' => NULL,
                'post_status' => '7',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => '20',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-07-10 14:43:03',
                'post_modified_gmt' => '2023-07-10 14:43:03',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => 1,
                'post_type' => 'menu',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64ac4327228e7',
            ),
            18 => 
            array (
                'ID' => 28,
                'post_author' => NULL,
                'post_date' => '2023-07-10 14:46:20',
                'post_date_gmt' => '2023-07-10 14:46:20',
                'post_content' => NULL,
                'post_title' => 'leilão teste 5',
                'post_excerpt' => NULL,
                'post_status' => '7',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => '20',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-07-10 14:46:20',
                'post_modified_gmt' => '2023-07-10 14:46:20',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => 2,
                'post_type' => 'menu',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64ac43ec74841',
            ),
            19 => 
            array (
                'ID' => 29,
                'post_author' => NULL,
                'post_date' => '2023-07-10 14:46:41',
                'post_date_gmt' => '2023-07-10 14:46:41',
                'post_content' => NULL,
                'post_title' => 'leilão teste 5',
                'post_excerpt' => NULL,
                'post_status' => '7',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => '20',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-07-10 14:46:41',
                'post_modified_gmt' => '2023-07-10 14:46:41',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => 3,
                'post_type' => 'menu',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64ac4401b0d8f',
            ),
            20 => 
            array (
                'ID' => 31,
                'post_author' => 1,
                'post_date' => '2023-07-11 03:59:47',
                'post_date_gmt' => '2023-07-11 03:59:47',
                'post_content' => '<p>Agora mais um teste</p>',
                'post_title' => 'Repasse do Contrato CPS.ACJF.ADM.2021.0941',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'repasse-do-contrato-cps.acjf.adm.2021.0941',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-10-18 17:42:26',
                'post_modified_gmt' => '2023-07-11 03:59:47',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'produtos',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"cliente":"3","total_horas":"25","valor_r":"R$ 4.251,00","incremento":"R$ 100,00","valor_venda":"R$ 5.000,00","valor_atual":"R$ 8.000,00"}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64acfd996e0bf',
            ),
            21 => 
            array (
                'ID' => 35,
                'post_author' => 1,
                'post_date' => '2023-07-13 18:45:22',
                'post_date_gmt' => '2023-07-13 18:45:22',
                'post_content' => '<p>descriptio de teste<br></p>',
                'post_title' => 'Repasse do Contrato CPS.ACJF.ADM.2021.0941',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'repasse-do-contrato-cps.acjf.adm.2021.0941',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-07-13 19:11:38',
                'post_modified_gmt' => '2023-07-13 18:45:22',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'produtos',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"cliente":"6","total_horas":"12","valor_r":"R$ 8.502,22"}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64b07009b7ab7',
            ),
            22 => 
            array (
                'ID' => 37,
                'post_author' => 1,
                'post_date' => '2023-07-13 19:58:56',
                'post_date_gmt' => '2023-07-13 19:58:56',
                'post_content' => '[sc ac="leiloes_publicos"]',
                'post_title' => 'Leiloes publicos',
                'post_excerpt' => 'descrição curta da página Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu ornare risus. Phasellus sed dolor mi. Donec laoreet convallis diam sed luctus.',
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'leiloes-publicos',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-12 16:54:20',
                'post_modified_gmt' => '2023-07-13 19:58:56',
                'post_content_filtered' => NULL,
                'post_parent' => 95,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'paginas',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"tipo_pagina":"leiloes_publicos"}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64b08191e1f58',
            ),
            23 => 
            array (
                'ID' => 38,
                'post_author' => NULL,
                'post_date' => '2023-07-13 19:58:57',
                'post_date_gmt' => '2023-07-13 19:58:57',
                'post_content' => NULL,
                'post_title' => 'Leiloes publicados',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => '37',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-07-13 19:58:57',
                'post_modified_gmt' => '2023-07-13 19:58:57',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => 4,
                'post_type' => 'menu',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64b081b13bc99',
            ),
            24 => 
            array (
                'ID' => 42,
                'post_author' => 1,
                'post_date' => '2023-07-18 16:51:44',
                'post_date_gmt' => '2023-07-18 16:51:44',
                'post_content' => '<p>Teste de horas<br></p>',
                'post_title' => 'Repasse do Contrato CPS.ACJF.ADM.2021.0948',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'repasse-do-contrato-cps.acjf.adm.2021.0948',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-07-18 16:51:44',
                'post_modified_gmt' => '2023-07-18 16:51:44',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => NULL,
                'post_type' => 'produtos',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => '{"cliente":"6","total_horas":"45","valor_r":"R$ 5.420,00"}',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '64b6ecdab4d00',
            ),
            25 => 
            array (
                'ID' => 64,
                'post_author' => NULL,
                'post_date' => '2023-10-19 19:50:10',
                'post_date_gmt' => '2023-10-19 19:50:10',
                'post_content' => NULL,
                'post_title' => 'Termos do site',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => '63',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2023-10-19 19:50:10',
                'post_modified_gmt' => '2023-10-19 19:50:10',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => 5,
                'post_type' => 'menu',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '6531b2a23764e',
            ),
            26 => 
            array (
                'ID' => 91,
                'post_author' => 1,
                'post_date' => '2024-01-09 00:00:00',
                'post_date_gmt' => '2024-01-09 13:45:31',
                'post_content' => NULL,
                'post_title' => NULL,
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'contrato.jpg',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-09 13:45:31',
                'post_modified_gmt' => '2024-01-09 13:45:31',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => 'media/2024/01/contrato.jpg',
                'menu_order' => NULL,
                'post_type' => 'attachment',
                'post_mime_type' => 'image/jpeg',
                'comment_count' => NULL,
                'config' => '"{\\"extenssao\\":\\"jpg\\"}"',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => NULL,
            ),
            27 => 
            array (
                'ID' => 92,
                'post_author' => 1,
                'post_date' => '2024-01-09 00:00:00',
                'post_date_gmt' => '2024-01-09 13:45:32',
                'post_content' => NULL,
                'post_title' => NULL,
                'post_excerpt' => NULL,
                'post_status' => 'trash',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'leilao-aeroclube-de-juiz-de-fora.jpg',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-10 11:39:04',
                'post_modified_gmt' => '2024-01-09 13:45:32',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => 'media/2024/01/leilao-aeroclube-de-juiz-de-fora.jpg',
                'menu_order' => NULL,
                'post_type' => 'attachment',
                'post_mime_type' => 'image/jpeg',
                'comment_count' => NULL,
                'config' => '"{\\"extenssao\\":\\"jpg\\"}"',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => NULL,
            ),
            28 => 
            array (
                'ID' => 93,
                'post_author' => 1,
                'post_date' => '2024-01-10 00:00:00',
                'post_date_gmt' => '2024-01-10 11:39:22',
                'post_content' => NULL,
                'post_title' => NULL,
                'post_excerpt' => NULL,
                'post_status' => 'trash',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'leilao-aeroclube-de-juiz-de-fora.jpg',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-10 11:39:31',
                'post_modified_gmt' => '2024-01-10 11:39:22',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => 'media/2024/01/leilao-aeroclube-de-juiz-de-fora.jpg',
                'menu_order' => NULL,
                'post_type' => 'attachment',
                'post_mime_type' => 'image/jpeg',
                'comment_count' => NULL,
                'config' => '"{\\"extenssao\\":\\"jpg\\"}"',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => NULL,
            ),
            29 => 
            array (
                'ID' => 94,
                'post_author' => 1,
                'post_date' => '2024-01-10 00:00:00',
                'post_date_gmt' => '2024-01-10 11:48:58',
                'post_content' => NULL,
                'post_title' => NULL,
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'leilao-aeroclube-de-juiz-de-fora.jpg',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-10 11:48:58',
                'post_modified_gmt' => '2024-01-10 11:48:58',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => 'media/2024/01/leilao-aeroclube-de-juiz-de-fora.jpg',
                'menu_order' => NULL,
                'post_type' => 'attachment',
                'post_mime_type' => 'image/jpeg',
                'comment_count' => NULL,
                'config' => '"{\\"extenssao\\":\\"jpg\\"}"',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => NULL,
            ),
            30 => 
            array (
                'ID' => 95,
                'post_author' => 1,
                'post_date' => '2024-01-10 00:00:00',
                'post_date_gmt' => '2024-01-10 11:51:39',
                'post_content' => NULL,
                'post_title' => NULL,
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => 'leilao-aeroclube-de-juiz-de-fora.jpg',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-01-10 11:51:39',
                'post_modified_gmt' => '2024-01-10 11:51:39',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => 'media/2024/01/leilao-aeroclube-de-juiz-de-fora.jpg',
                'menu_order' => NULL,
                'post_type' => 'attachment',
                'post_mime_type' => 'image/jpeg',
                'comment_count' => NULL,
                'config' => '"{\\"extenssao\\":\\"jpg\\"}"',
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => NULL,
            ),
            31 => 
            array (
                'ID' => 103,
                'post_author' => NULL,
                'post_date' => '2024-02-01 11:19:21',
                'post_date_gmt' => '2024-02-01 11:19:21',
                'post_content' => NULL,
                'post_title' => 'Contato',
                'post_excerpt' => NULL,
                'post_status' => 'publish',
                'comment_status' => NULL,
                'ping_status' => NULL,
                'post_password' => NULL,
                'post_name' => '102',
                'to_ping' => NULL,
                'pinged' => NULL,
                'post_modified' => '2024-02-01 11:19:21',
                'post_modified_gmt' => '2024-02-01 11:19:21',
                'post_content_filtered' => NULL,
                'post_parent' => NULL,
                'guid' => NULL,
                'menu_order' => 7,
                'post_type' => 'menu',
                'post_mime_type' => NULL,
                'comment_count' => NULL,
                'config' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'token' => '65bba869db135',
            ),
        ));
        
        
    }
}